matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: 
           -'ubuntu-toolchain-r-test'
          packages: 
           - 'g++-5'
      env: COMPILER=g++-5
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: 
           - 'ubuntu-toolchain-r-test'
           - 'llvm-toolchain-precise-3.7'
          packages: 
           - 'clang-3.7'
      env: COMPILER=clang++-3.7
    - os: osx
      compiler: clang
      env: COMPILER=clang++

language: r 
warnings_are_errors: false
sudo: required
cache: packages
r_github_packages:
  - hadley/purrr
  - hadley/dplyr
  - eddelbuettel/BH     
  
after_success:
  - Rscript -e 'covr::codecov()'
