# Sample .travis.yml for R projects

language: r
warnings_are_errors: false
sudo: required
r_github_packages:
  - jayhesselberth/dplyr
compiler:
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - clang
r_packages:
  - covr
after_success:
  - Rscript -e 'covr::codecov()'
