language: r
warnings_are_errors: false
cache: packages

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      addons:
        apt:
          sources: 
           -'ubuntu-toolchain-r-test'
          packages: 
           - 'g++-5'
      env: COMPILER=g++-5
    - os: linux
      compiler: clang
      dist: trusty
      sudo: required
      addons:
        apt:
          sources: 
           - 'ubuntu-toolchain-r-test'
           - 'llvm-toolchain-precise-3.7'
          packages: 
           - 'clang-3.7'
      env: COMPILER=clang++-3.7
    - os: osx
      compiler: clang
      sudo: required
      env: COMPILER=clang++

after_success:
  - Rscript -e 'covr::codecov()'
