dist: trusty
sudo: required
language: r
warnings_are_errors: false
cache: packages
r:
  - oldrel
  - release
  - devel

# based on: https://github.com/wesm/feather/issues/154
matrix:
  include:
    - os: linux
      r:
        - oldrel
        - release
        - devel
      compiler: gcc-6
      addons:
        apt:
          sources: 
           - 'ubuntu-toolchain-r-test'
          packages: 
           - 'g++-6'
      before_install: |
        mkdir ~/.R
        cat <<EOF > ~/.R/Makevars
        CXX1X=g++-6
        CXX1XSTD=-std=c++11
     
    - os: linux
      r:
        - oldrel
        - release
        - devel
      compiler: clang-3.7
      addons:
        apt:
          sources: 
            - 'ubuntu-toolchain-r-test'
            - 'llvm-toolchain-precise-3.7'
          packages: 
            - 'clang-3.7'
      before_install: |
        mkdir ~/.R
        cat <<EOF > ~/.R/Makevars
        CXX1X=clang++-3.7
        CXX1XSTD=-std=c++11
    - os: osx
      r:
        - oldrel
        - release
        - devel
      compiler: clang

after_success:
  - Rscript -e 'covr::codecov()'
