dist: trusty
sudo: required
language: r
warnings_are_errors: false
cache: packages

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: 
           - 'ubuntu-toolchain-r-test'
          packages: 
           - 'g++-5'
      before_script:
        - export CXX="g++-5"
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: 
           - 'ubuntu-toolchain-r-test'
           - 'llvm-toolchain-precise-3.7'
          packages: 
           - 'clang-3.7'
      before_script:
        - export CXX="clang++-3.7"
    - os: osx
      compiler: clang

after_success:
  - Rscript -e 'covr::codecov()'
